function REACTION_EQUATIONS_MOCK_SPECIES(model)
%%%% add reactions that do not consume any species but produce an
%%%% additional C3a species with a flag for the respective C3 convertase
%%%% -> allows to evaluate the degree of activitiy of the different
%%%% convertases

r27_Mock  = addreaction(model, '[C3] -> [C3] + [C3a_H2O]', ...
                   'ReactionRate', '[k_C3_cat_C3(H2O)Bb] * [C3] * [C3(H2O)Bb fluid] / ([K_C3_m_C3(H2O)Bb] + [C3])', 'Name', 'r27_Mock');
        
r28_Mock  = addreaction(model, '[C3] + [C3bBb fluid] -> [C3] + [C3bBb fluid] + [C3a_C3bBb_fluid]', ...
                   'ReactionRate', '[k_C3_cat_C3bBb] * [C3] * [C3bBb fluid] / ([K_C3_m_C3bBb] + [C3])', 'Name', 'r28_Mock');
               
pr14_Mock = addreaction(model, '[C3] + [C3bBbP host] -> [C3] + [C3bBbP host] + [C3a_C3bBbP_host]', ...
                   'ReactionRate', '[k_C3_cat_C3bBbP] * [C3] * [C3bBbP host] / ([K_C3_m_C3bBbP] + [C3])', 'Name', 'pr14_Mock');  
  
r30_Mock  = addreaction(model, '[C3] + [C3bBb host] -> [C3] + [C3bBb host] + [C3a_C3bBb_host]', ...
                   'ReactionRate', '[k_C3_cat_C3bBb] * [C3] * [C3bBb host] / ([K_C3_m_C3bBb] + [C3])', 'Name', 'r30_Mock');
             
               
               
% r12_Mock = addreaction(model, 'nfC3b + H2O -> nfC3b + H2O + C3b_nfC3b_H2O', 'ReactionRate',... 
%                                 'k_p_fC3b * nfC3b * H2O', 'Name', 'r12_Mock');
r12_Mock = addreaction(model, 'nfC3b -> nfC3b + C3b_nfC3b_H2O', 'ReactionRate',... 
                                'k_p_fC3b * nfC3b', 'Name', 'r12_Mock');
                        
% r13_Mock = addreaction(model, 'nhC3b + H2O -> nhC3b + H2O + C3b_nhC3b_H2O', 'ReactionRate',... 
%                                 'k_p_fC3b * nhC3b * H2O', 'Name', 'r13_Mock');
r13_Mock = addreaction(model, 'nhC3b -> nhC3b + C3b_nhC3b_H2O', 'ReactionRate',... 
                                'k_p_fC3b * nhC3b', 'Name', 'r13_Mock');
                            
r29_Mock = addreaction(model, '[nfC3b] + [Surface host] -> [nfC3b] + [Surface host] + C3b_nfC3b_host', 'ReactionRate',... 
                   '[k_p_C3b_surface] * [nfC3b] * [Surface host]', 'Name', 'r29_Mock');
               
r31_Mock = addreaction(model, '[nhC3b] + [Surface host] -> [nhC3b] + [Surface host] + C3b_nhC3b_host', 'ReactionRate',... 
                   '[k_p_hC3b] * [nhC3b] * [Surface host] * 15.6', 'Name', 'r31_Mock');
               
               
               
r2_Mock = addreaction(model, '[C3(H2O) fluid] + B -> [C3(H2O) fluid] + B + C3H2OB_mock',... 
    'ReactionRate', '[k_p_C3(H20)B]  * [C3(H2O) fluid] * B', 'Name', 'r2_Mock');

r14_Mock = addreaction(model, '[C3b fluid] + B -> [C3b fluid] + B + C3bBf', 'ReactionRate',... 
                   'k_p_C3bB * [C3b fluid] * B', 'Name', 'r14_Mock');
               
r36_Mock = addreaction(model, '[C3b host] + B ->  [C3b host] + B + C3bBh', 'ReactionRate',... 
                   '[k_p_C3bB] * [C3b host] * B', 'Name', 'r36_Mock');   
               

r10_Mock = addreaction(model, '[C3(H2O)B fluid] + D -> [C3(H2O)B fluid] + D + Ba_H2O', 'ReactionRate',... 
'[k_D_cat_C3(H2O)B] * D * [C3(H2O)B fluid] / ([K_D_m_C3(H2O)B] + [C3bB fluid] + [C3(H2O)B fluid] + [C3bB host])',...
'Name', 'r10_Mock');   

r24_Mock = addreaction(model, '[C3bB fluid] + D -> [C3bB fluid] + D + Ba_C3bB_fluid', 'ReactionRate',... 
'[k_D_cat_C3bB] * D * [C3bB fluid] / ([K_D_m_C3bB] + [C3bB fluid] + [C3(H2O)B fluid] + [C3bB host])',...
'Name', 'r24_Mock');   

pr24_Mock = addreaction(model, '[C3bBP host] + D -> [C3bBP host] + D + Ba_C3bBP_host', 'ReactionRate',... 
     '[k_D_cat_C3bB] * D * [C3bBP host] / ([K_D_m_C3(H2O)B] + [C3bB fluid] + [C3(H2O)B fluid] + [C3bB host]+ [C3bBP host])',...
       'Name', 'pr24_Mock');       
   
r41_Mock = addreaction(model, '[C3bB host] + D -> [C3bB host] + D + Ba_C3bB_host', 'ReactionRate',... 
       '[k_D_cat_C3bB] * D * [C3bB host] / ([K_D_m_C3(H2O)B] + [C3bB fluid] + [C3(H2O)B fluid] + [C3bB host]+ [C3bBP host])',...
       'Name', 'r41_Mock');  

   
r10_Mock2 = addreaction(model, '[C3(H2O)B fluid] + D -> [C3(H2O)B fluid] + D + Bb_H2O', 'ReactionRate',... 
'[k_D_cat_C3(H2O)B] * D * [C3(H2O)B fluid] / ([K_D_m_C3(H2O)B] + [C3bB fluid] + [C3(H2O)B fluid] + [C3bB host])',...
'Name', 'r10_Mock2');   

r24_Mock2 = addreaction(model, '[C3bB fluid] + D -> [C3bB fluid] + D + Bb_C3bB_fluid', 'ReactionRate',... 
'[k_D_cat_C3bB] * D * [C3bB fluid] / ([K_D_m_C3bB] + [C3bB fluid] + [C3(H2O)B fluid] + [C3bB host])',...
'Name', 'r24_Mock2');   

pr24_Mock2 = addreaction(model, '[C3bBP host] + D -> [C3bBP host] + D + Bb_C3bBP_host', 'ReactionRate',... 
     '[k_D_cat_C3bB] * D * [C3bBP host] / ([K_D_m_C3(H2O)B] + [C3bB fluid] + [C3(H2O)B fluid] + [C3bB host]+ [C3bBP host])',...
       'Name', 'pr24_Mock2');       
   
r41_Mock2 = addreaction(model, '[C3bB host] + D -> [C3bB host] + D + Bb_C3bB_host', 'ReactionRate',... 
       '[k_D_cat_C3bB] * D * [C3bB host] / ([K_D_m_C3(H2O)B] + [C3bB fluid] + [C3(H2O)B fluid] + [C3bB host]+ [C3bBP host])',...
       'Name', 'r41_Mock2');  
   
   
   
   
r52_Mock = addreaction(model, '[iC3bCR1 fluid] + I -> [iC3bCR1 fluid] + I + [C3dg_fluid_Mock]', 'ReactionRate',... 
'[k_FI_cat_C3bH] * I * [iC3bCR1 fluid] / ([K_FI_m_C3bH] + [C3bH fluid] + [C3bCR1 fluid] + [iC3bCR1 fluid] + [C3bH host] + [C3bCR1 host] + [iC3bCR1 host])',...
'Name', 'r52_Mock');             
   
r48_Mock = addreaction(model, '[iC3bCR1 host]  + I ->[iC3bCR1 host]  + I + C3dg_host_Mock', 'ReactionRate',... 
   '[k_FI_cat_C3bH] * I * [iC3bCR1 host] / ([K_FI_m_C3bH] + [C3bH fluid] + [C3bCR1 fluid] + [iC3bCR1 fluid] + [C3bH host] + [C3bCR1 host] + [iC3bCR1 host])',...
   'Name', 'r48_Mock');         



r45_Mock = addreaction(model, '[C3bCR1 host] + I -> [C3bCR1 host] + I + iC3b_host_Mock', 'ReactionRate',... 
       '[k_FI_cat_C3bH] * I * [C3bCR1 host] / ([K_FI_m_C3bH] + [C3bH fluid] + [C3bCR1 fluid] + [iC3bCR1 fluid] + [C3bH host] + [C3bCR1 host] + [iC3bCR1 host])',...
       'Name', 'r45_Mock');       
r47_Mock = addreaction(model, '[C3bH host] + I -> [C3bH host] + I + iC3b_host_Mock', 'ReactionRate',... 
       '[k_FI_cat_C3bH] * I * [C3bH host] / ([K_FI_m_C3bH] + [C3bH fluid] + [C3bCR1 fluid] + [iC3bCR1 fluid] + [C3bH host] + [C3bCR1 host] + [iC3bCR1 host])',...
       'Name', 'r47_Mock');           
   
   


   
   