function REACTION_PARAMETER(model, C5_concvertase_original)

                    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Parameters
k_p_C3H20            = addparameter(model, 'k_p_C3(H20)', 8.3e-7,...
                        'notes', 'Hydrolysis of C3(H2O) [1]', 'ValueUnits', '1/second');
k_p_C3H20_B          = addparameter(model, 'k_p_C3(H20)B', 21.3e4,...
                        'notes', 'Association of Factor B to C3(H2O) [E1]', 'ValueUnits', '1/molarity/second');
k_m_C3H20_B          = addparameter(model, 'k_m_C3(H20)B', 15.5e-2,...
                        'notes', 'Dissociation of complex C3(H2O)B [E1]', 'ValueUnits', '1/second');
k_p_C3bH             = addparameter(model, 'k_p_C3bH', 5.2e6,...
                        'notes', 'Association of Factor H to C3(H2O) [E1]', 'ValueUnits', '1/molarity/second');
k_m_C3bH             = addparameter(model, 'k_m_C3bH', 32.5,...
                        'notes', 'Dissociation of complex C3(H2O)H [E1]', 'ValueUnits', '1/second');
                    
k_p_C3bH_surf             = addparameter(model, 'k_p_C3bH_surf', 5.2e6,...
                        'notes', 'Association of Factor H to surface bound proteins', 'ValueUnits', '1/molarity/second');
                    
k_p_C3bCR1           = addparameter(model, 'k_p_C3bCR1', 1.2e4,...
                        'notes', 'Association of CR1 to C3b [E2, 7, 8, 9]', 'ValueUnits', '1/molarity/second');
k_m_C3bCR1           = addparameter(model, 'k_m_C3bCR1', 1e-2,...
                        'notes', 'Dissociation of complex C3bCR1 [E2, 7, 8, 9]', 'ValueUnits', '1/second');
k_m_C3H2O_Bb         = addparameter(model, 'k_m_C3(H2O)Bb', 9e-3,...
                        'notes', 'Dissociation of complex C3(H2O)Bb  [2]', 'ValueUnits', '1/second');                  
k_m_C3bBbH_decay     = addparameter(model, 'k_m_C3bBbH decay', 7.7e-2,...
                        'notes', 'k_c', 'ValueUnits', '1/second');         
                    
% k_p_fC3b             = addparameter(model, 'k_p_fC3b', 4.2e8,...
%                         'notes', 'Association of nfC3b, nhC3b, and npC3b to water [C1]', 'ValueUnits', '1/molarity/second');    
k_p_fC3b             = addparameter(model, 'k_p_fC3b', 1.2e4,...
                        'notes', 'Association of nfC3b, nhC3b, and npC3b to water [C1]', 'ValueUnits', '1/second');   
                    
k_p_C3bB             = addparameter(model, 'k_p_C3bB', 21.3e4,...
                        'notes', 'Association of Factor B to C3b [3]', 'ValueUnits', '1/molarity/second');   
k_m_C3bB             = addparameter(model, 'k_m_C3bB', 15.5e-2,...
                        'notes', 'Dissociation of complex C3bB [3]', 'ValueUnits', '1/second');                    
k_m_C3bBb            = addparameter(model, 'k_m_C3bBb', 7.7e-3,...
                        'notes', 'Dissociation of complex C3bBb  [2]', 'ValueUnits', '1/second'); 
% This is on the host cell. No fluid phase parameter is given CHECK
k_m_C3bBbCR1_decay   = addparameter(model, 'k_m_C3bBbCR1 decay', 7.7e-2,...
                        'notes', 'Decay of C3 convertase by inhibitor CR1 on host cell [Assumption]', 'ValueUnits', '1/second');                 
k_p_C3bBbC3b         = addparameter(model, 'k_p_C3bBbC3b', 3.5e6,...
                        'notes', 'Association of C3b to C3bBb [5, Optimization]', 'ValueUnits', '1/molarity/second'); 
k_m_C3bBbC3b         = addparameter(model, 'k_m_C3bBbC3b', 3.8e-3,...
                        'notes', 'Dissociation of complex C3bBbC3b  [12]', 'ValueUnits', '1/second'); 
k_m_C3bBbDAF_decay   = addparameter(model, 'k_m_C3bBbDAF decay', 7.7e-2,...
                        'notes', 'Decay of C3 convertase by inhibitor DAF on cell [Assumption]', 'ValueUnits', '1/second');
                    
k_p_C3b_surface      = addparameter(model, 'k_p_C3b_surface', 4.2e8,...
                        'notes', 'Attachment of nfC3b to host cell [Calculated]', 'ValueUnits', '1/molarity/second');  
                    
k_p_hC3b             = addparameter(model, 'k_p_hC3b', 4.2e8,...
                        'notes', 'Attachment of nhC3b to cell [Calculated]', 'ValueUnits', '1/molarity/second');                            
% k_p_hC3b             = addparameter(model, 'k_p_hC3b', 4.2e8 * 15.6,...
%                         'notes', 'Attachment of nhC3b to cell [Calculated]', 'ValueUnits', '1/molarity/second');
                    
k_p_C5b7_surface     = addparameter(model, 'k_p_C5b7 surface', 4.2e8,...
                        'notes', 'Attachment of C5b7 to cell [Calculated]', 'ValueUnits', '1/molarity/second');                     
k_p_C3bBbDAF         = addparameter(model, 'k_p_C3bBbDAF', 2.0e3,...
                        'notes', 'Association of DAF to C3 convertase on cell [E3, 10]', 'ValueUnits', '1/molarity/second');                              
k_p_iC3bCR1          = addparameter(model, 'k_p_iC3bCR1', 2e3,...
                        'notes', 'Association of iC3b to CR1 [E4, 8, 11]', 'ValueUnits', '1/molarity/second');
k_m_iC3bCR1          = addparameter(model, 'k_m_iC3bCR1', 1.0e-2,...
                        'notes', 'Dissociation of complex iC3bCR1 [E4, 8, 11]', 'ValueUnits', '1/second');                       
if C5_concvertase_original
    k_p_C3bBbC3bC5       = addparameter(model, 'k_p_C3bBbC3bC5', 5.0e6,...
                        'notes', 'Association of C5 to C3bBbC3b [13]', 'ValueUnits', '1/molarity/second');   
    k_m_C3bBbC3bC5       = addparameter(model, 'k_m_C3bBbC3bC5', 1.0e-2,...
                        'notes', 'Dissociation of complex C3bBbC3bC5  [13]', 'ValueUnits', '1/second');
end
% k_m_C5b == k_m_C3bBbC3bC5b
k_m_C5b              = addparameter(model, 'k_m_C5b', 3.8e-2,...
                        'notes', 'Dissociation of complex C3bBbC3bC5b [14]', 'ValueUnits', '1/second');  
% Check what the right value is
k_p_C5b7             = addparameter(model, 'k_p_C5b7', 7.3e5,...
                        'notes', 'Association of C7 to C3bBbC3bC5bC6 [5, 15, 16]', 'ValueUnits', '1/molarity/second');  
k_m_C5b7             = addparameter(model, 'k_m_C5b7', 8e-7,...
                        'notes', 'Dissociation of complex C3bBbC3bC5bC6C7  [5, 15, 16]', 'ValueUnits', '1/second');  
k_p_C5b8             = addparameter(model, 'k_p_C5b8', 1.1e6,...
                        'notes', 'Association of C8 to C5b7  [5, 15, 16]', 'ValueUnits', '1/molarity/second');  
k_m_C5b8             = addparameter(model, 'k_m_C5b8', 9.8e-7,...
                        'notes', 'Dissociation of complex C5b8  [5, 15, 16]', 'ValueUnits', '1/second');  
k_p_C5b9             = addparameter(model, 'k_p_C5b9', 2.8e6,...
                        'notes', 'Association of C9 to C5b8  [5, 15, 16]', 'ValueUnits', '1/molarity/second'); 
k_m_C5b9             = addparameter(model, 'k_m_C5b9', 1e-6,...
                        'notes', 'Dissociation of complex C5b9  [5, 15, 16]', 'ValueUnits', '1/second');                      
k_p_CD59C5b9         = addparameter(model, 'k_p_CD59C5b9', 1.0e6,...
                        'notes', 'Association of CD59 to C5b9 [Assumption]', 'ValueUnits', '1/molarity/second');                          
k_m_CD59C5b9         = addparameter(model, 'k_m_CD59C5b9', 2.0e-4,...
                        'notes', 'Dissociation of complex CD59C5b9  [Assumption]', 'ValueUnits', '1/second');                      
k_p_C3bBbC3bC5bC6    = addparameter(model, 'k_p_C3bBbC3bC5bC6', 6.0e4,...
                        'notes', 'Association of C6 to C3bBbC3bC5b  [5, 15]', 'ValueUnits', '1/molarity/second');  
k_m_C3bBbC3bC5bC6    = addparameter(model, 'k_m_C3bBbC3bC5bC6', 9e-8,...
                        'notes', 'Dissociation of complex C3bBbC3bC5bC6  [5, 15]', 'ValueUnits', '1/second'); 
k_p_C5b7_micelle     = addparameter(model, 'k_p_C5b7 micelle', 69.3,...
                        'notes', 'Formation of C5b7 micelle in fluid [16]', 'ValueUnits', '1/second');  
k_p_CnC5b7           = addparameter(model, 'k_p_CnC5b7', 4.1e5,...
                        'notes', 'Association of Cn to C5b7 [E5]', 'ValueUnits', '1/molarity/second');  
k_m_CnC5b7           = addparameter(model, 'k_m_CnC5b7', 4.0e-3,...
                        'notes', 'Dissociation of complex CnC5b7 [E5]', 'ValueUnits', '1/second');    
k_p_VnC5b7           = addparameter(model, 'k_p_VnC5b7', 2.4e5,...
                        'notes', 'Association of Vn to C5b7 [5, 17]', 'ValueUnits', '1/molarity/second');                      
k_m_VnC5b7           = addparameter(model, 'k_m_VnC5b7', 2.0e-3,...
                        'notes', 'Dissociation of complex VnC5b7 [Assumption]', 'ValueUnits', '1/second'); 
k_p_VnC5b8           = addparameter(model, 'k_p_VnC5b8', k_p_C5b8.Value,...
                        'notes', 'Association of C8 to VnC5b7 [A1]', 'ValueUnits', '1/molarity/second');      
k_m_VnC5b8           = addparameter(model, 'k_m_VnC5b8', k_m_C5b8.Value,...
                        'notes', 'Dissociation of complex VnC5b8  [A1]', 'ValueUnits', '1/second');                   
k_p_VnC5b9           = addparameter(model, 'k_p_VnC5b9', k_p_C5b9.Value,...
                        'notes', 'Association of C9 to VnC5b8  [A2]', 'ValueUnits', '1/molarity/second');   
k_m_VnC5b9           = addparameter(model, 'k_m_VnC5b9',  k_m_C5b9.Value,...
                        'notes', 'Dissociation of complex VnC5b9  [A2]', 'ValueUnits', '1/second');                   
k_p_CnC5b8           = addparameter(model, 'k_p_CnC5b8', k_p_C5b8.Value,...
                        'notes', 'Association of Cn to C5b8  [A3]', 'ValueUnits', '1/molarity/second');  
k_m_CnC5b8           = addparameter(model, 'k_m_CnC5b8', k_p_C5b7.Value,...
                        'notes', 'Dissociation of complex CnC5b8  [A3]', 'ValueUnits', '1/second');                     
k_p_CnC5b9           = addparameter(model, 'k_p_CnC5b9', k_p_C5b9.Value,...
                        'notes', 'Association of C9 to CnC5b8 [A4]', 'ValueUnits', '1/molarity/second');                  
k_m_CnC5b9           = addparameter(model, 'k_m_CnC5b9', k_m_C5b9.Value,...
                        'notes', 'Dissociation of complex CnC5b9 [A4]', 'ValueUnits', '1/second');                  
% Parameters for Michaelis-Menten type of reactions
k_D_cat_C3_H2O_B     = addparameter(model, 'k_D_cat_C3(H2O)B', 2.1,...
                        'notes', 'Activation of complex C3(H2O)B by enzyme Factor D [E6]', 'ValueUnits', '1/second'); 
K_D_m_C3_H2O_B       = addparameter(model, 'K_D_m_C3(H2O)B', 0.1e-6,...
                        'notes', 'Activation of complex C3(H2O)B by enzyme Factor D [E6]', 'ValueUnits', 'molarity'); 
k_D_cat_C3bB         = addparameter(model, 'k_D_cat_C3bB', 2.1,...
                        'notes', 'Activation of complex C3bB by enzyme Factor D [5, Optimization]', 'ValueUnits', '1/second'); 
K_D_m_C3bB           = addparameter(model, 'K_D_m_C3bB', 0.1e-6,...
                        'notes', 'Activation of complex C3bB by enzyme Factor D [5, Optimization]', 'ValueUnits', 'molarity');      
k_C3_cat_C3_H2O_Bb   = addparameter(model, 'k_C3_cat_C3(H2O)Bb', 1.8,...
                        'notes', 'Cleavage of C3 by C3 convertase C3(H20)Bb [5, Optimization],', 'ValueUnits', '1/second');    
K_C3_m_C3_H2O_Bb     = addparameter(model, 'K_C3_m_C3(H2O)Bb', 5.9e-6,...
                        'notes', 'Cleavage of C3 by C3 convertase C3(H20)Bb [5, Optimization] Optimization,', 'ValueUnits', 'molarity');                       
k_C3_cat_C3bBb       = addparameter(model, 'k_C3_cat_C3bBb', 1.8,...
                        'notes', 'Cleavage of C3 by C3 convertase C3bBb [2],', 'ValueUnits', '1/second');    
K_C3_m_C3bBb         = addparameter(model, 'K_C3_m_C3bBb', 5.9e-6,...
                        'notes', 'Cleavage of C3 by C3 convertase C3bBb [2],', 'ValueUnits', 'molarity');
k_FI_cat_C3bH        = addparameter(model, 'k_FI_cat_C3bH', 1.3,...
                        'notes', 'Cleavage of C3b by inhibitor Factor I [6]', 'ValueUnits', '1/second');                    
K_FI_m_C3bH          = addparameter(model, 'K_FI_m_C3bH', 2.5e-7,...
                        'notes', 'Cleavage of C3b by inhibitor Factor I [6]', 'ValueUnits', 'molarity');                        
if C5_concvertase_original
    k_C5_cat_C3bBbC3b    = addparameter(model, 'k_C5_cat_C3bBbC3b', 4.8,...
                        'notes', 'Cleavage of C5 by C5 convertase C3bBbC3b [5, 18],', 'ValueUnits', '1/second');     
else
    k_C5_cat_C3bBbC3b = addparameter(model, 'k_C5_cat_C3bBbC3b', 0.003,...
                        'notes', 'Cleavage of C5 by C5 convertase C3bBbC3b,', 'ValueUnits', '1/second');    
    K_C5_m_C3bBbC3b   = addparameter(model, 'K_C5_m_C3bBbC3b', 0.016e-6,...
                        'notes', 'Cleavage of C5 by C5 convertase C3bBbC3b,', 'ValueUnits', 'molarity');      
end

% Properdin parameters
k_p_C3bP              = addparameter(model, 'k_p_C3bP', 3e6,...
                        'notes', 'Association of P to C3b on cell [5, Optimization]', 'ValueUnits', '1/molarity/second');                                     
k_m_C3bP              = addparameter(model, 'k_m_C3bP', 5e-4,...
                        'notes', 'Dissociation of C3bP on cell [4]', 'ValueUnits', '1/second'); 

% Missing in publication. This was set to the same value as k_p_C3bB
k_p_C3bBP             = addparameter(model, 'k_p_C3bBP', 21.3e4,...
                        'notes', 'Association of Factor B to C3bP [was set to k_p_C3bB]', 'ValueUnits', '1/molarity/second');                                     

                    
k_m_C3bBbP            = addparameter(model, 'k_m_C3bBbP', 7.7e-4,...
                        'notes', 'Dissociation of complex C3bBbP [?]', 'ValueUnits', '1/second');
                        
k_p_iC3bP             = addparameter(model, 'k_p_iC3bP', 3e6,...
                        'notes', 'Association of Properdin to iC3b [5] Optimization', 'ValueUnits', '1/molarity/second');                                     
k_m_iC3bP             = addparameter(model, 'k_m_iC3bP', 3.8e-4,...
                        'notes', 'Dissociation of from iC3b [4]', 'ValueUnits', '1/second');                    
                                                      
k_C3_cat_C3bBbP       = addparameter(model, 'k_C3_cat_C3bBbP', 3.1,...
                        'notes', 'Cleavage of C3 by C3 convertase C3bBbP  [5, Optimization]', 'ValueUnits', '1/second');    
K_C3_m_C3bBbP         = addparameter(model, 'K_C3_m_C3bBbP', 1.8e-6,...
                        'notes', 'Cleavage of C3 by C3 convertase C3bBbP [5, Optimization]', 'ValueUnits', 'molarity');              
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
